apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    project: roboshop
    environment: dev
    component: frontend
  annotations:
    description: "This is created to demonstrate pod annotations"
    jenkis: "https://jenkins.com/build/job/roboshop-catalogue/3"
spec:
  containers:
  - name: nginx
    image: nginx